#!/bin/bash

REGISTRY=registry.giantswarm.io
COMPANY=giantswarm
PROJECT=docs-auth

build:
	docker build -t $(registry)/$(COMPANY)/$(PROJECT) .

run:
	docker run --name=$(PROJECT) --rm -p 80:80 \
		-e MKDOCSMASTER_PORT_8000_TCP_ADDR=$(MKDOCSMASTER_PORT_8000_TCP_ADDR) \
		-e MKDOCSMASTER_PORT_8000_TCP_PORT=$(MKDOCSMASTER_PORT_8000_TCP_PORT) \
		-e MKDOCSSLAVE_PORT_8000_TCP_ADDR=$(MKDOCSSLAVE_PORT_8000_TCP_ADDR) \
		-e MKDOCSSLAVE_PORT_8000_TCP_PORT=$(MKDOCSSLAVE_PORT_8000_TCP_PORT) \
		-e SITESEARCH_PORT_9200_TCP_ADDR=$(SITESEARCH_PORT_9200_TCP_ADDR) \
		-e SITESEARCH_PORT_9200_TCP_PORT=$(SITESEARCH_PORT_9200_TCP_PORT) \
		$(registry)/$(COMPANY)/$(PROJECT)

delete:
	docker stop $(PROJECT)
	docker rm $(PROJECT)
	docker rmi $(registry)/$(COMPANY)/$(PROJECT)
