version: 2.1

orbs:
  architect: giantswarm/architect@5.12.1

workflows:
  build-workflow:
    jobs:
    - architect/push-to-registries:
        context: architect
        name: push-to-registries
        filters:
          tags:
            only: /.*/

          branches:
            ignore:
            - main
            - master
    - architect/push-to-app-catalog:
        name: push-to-app-catalog
        context: architect
        app_catalog: giantswarm-operations-platform-catalog
        app_catalog_test: giantswarm-operations-platform-test-catalog
        chart: docs-proxy-app
        requires:
        - push-to-registries
          # Trigger job on git tag.
        filters:
          tags:
            only: /^v.*/
          branches:
            ignore:
            - main
            - master
