version: 2.1

orbs:
  architect: giantswarm/architect@4.34.1

jobs:
  build:
    executor: architect/architect
    environment:
      DOCKER_BUILDKIT: "1"

    steps:
      - checkout

      - setup_remote_docker:
          version: 20.10.11
      
      - architect/push-to-docker:
          image: quay.io/giantswarm/docs-proxy
          tag-latest-branch: main
          username_envar: QUAY_USERNAME
          password_envar: QUAY_PASSWORD

workflows:
  package-and-push-chart-on-tag:
    jobs:
      - build:
          context: architect
          filters:  # required since `architect/push-to-app-catalog` has tag filters AND requires `build`
            tags:
              only: /.*/

      - architect/push-to-app-catalog:
          name: package and push
          context: architect
          app_catalog: giantswarm-operations-platform-catalog
          app_catalog_test: giantswarm-operations-platform-test-catalog
          chart: docs-proxy-app
          # Trigger job on git tag.
          filters:
            tags:
              only: /^v.*/
          requires:
            - build
