version: 2.1

orbs:
  architect: giantswarm/architect@4.9.0

jobs:
  build:
    machine:
      image: "ubuntu-1604:201903-01"

    steps:
      - checkout
      
      - run:
          name: Install architect
          command: |
            wget -q $(curl -sS -H "Authorization: token $RELEASE_TOKEN" https://api.github.com/repos/giantswarm/architect/releases/tags/v1.0.0 | grep browser_download_url | head -n 1 | cut -d '"' -f 4)
            chmod +x ./architect
            ./architect version
      
      - run:
          name: Build
          command: ./architect build
      
      - deploy:
          name: Deploy (master only)
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              ./architect deploy
            fi

workflows:
  package-and-push-chart-on-tag:
    jobs:
      - build:
          filters:  # required since `architect/push-to-app-catalog` has tag filters AND requires `build`
            tags:
              only: /.*/
      - architect/push-to-app-catalog:
          name: "package and push the app"
          app_catalog: "giantswarm-operations-platform-catalog"
          app_catalog_test: "giantswarm-operations-platform-test-catalog"
          chart: "docs-proxy-app"
          # Trigger job on git tag.
          filters:
            tags:
              only: /^v.*/
          requires:
            - build
