name: docs-proxy-app
namespace: docs
image:
  name: docs-proxy
hostnames:
- docs.giantswarm.io
- docs.operations.awsprod.gigantic.io

resources:
  requests:
    cpu: 10m
    memory: 10Mi
    ephemeralStorage: 50Mi
  limits:
    cpu: 100m
    memory: 50Mi
    ephemeralStorage: 200Mi

ingress:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-giantswarm
    kubernetes.io/tls-acme: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
