apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.name }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  ingressClassName: nginx
  rules:
    {{- $serviceName := .Values.name -}}
    {{- range .Values.hostnames }}
    - host: {{ . }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ $serviceName }}
                port:
                  number: 8000
    {{- end }}
  tls:
    - hosts:
      {{- range .Values.hostnames }}
      - {{ . }}
      {{- end }}
      secretName: {{ .Values.name }}
