apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: proxy
  namespace: docs
  labels:
    app: docs
  annotations:
    certmanager.k8s.io/cluster-issuer: letsencrypt-prod
    kubernetes.io/tls-acme: "true"
spec:
  rules:
  - host: docs.giantswarm.io
    http:
      paths:
      - backend:
          serviceName: proxy
          servicePort: 8000
        path: /
  tls:
  - hosts:
    - docs.giantswarm.io
    secretName: docs-proxy
