kind: Service
apiVersion: v1
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ .Values.name }}
  labels:
    app: {{ .Values.image.namespace }}
    component: {{ .Values.image.name }}
spec:
  ports:
    - port: 8000
      targetPort: 8000
  selector:
    app: {{ .Values.image.namespace }}
    component: {{ .Values.image.name }}
