---
apiVersion: v1
kind: Secret
metadata:
  namespace: docs
  name: docs-proxy-pull-secret
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ .Values.Installation.V1.Secret.Registry.PullSecret.DockerConfigJSON | b64enc | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: giantswarm-cert
  namespace: docs
type: Opaque
data:
  ca: {{ .Values.Installation.V1.Secret.Certificate.GiantSwarm.CAPem | b64enc | quote }}
  crt: {{ .Values.Installation.V1.Secret.Certificate.GiantSwarm.CrtPem | b64enc | quote }}
  key: {{ .Values.Installation.V1.Secret.Certificate.GiantSwarm.KeyPem | b64enc | quote }}
