kind: Service
apiVersion: v1
metadata:
  namespace: docs
  name: proxy
  labels:
    app: docs
    component: proxy
    repo: giantswarm/docs-proxy
spec:
  ports:
    - port: 8000
      targetPort: 8000
  selector:
    app: docs
    component: proxy
